### PR TITLE
Move to 4.12

### PR DESCRIPTION
**Pull request by jgriffiths**
4.12 Is the minimum version provided by Fedora 23. Note I've
left the old 4.10 patch there in case 4.12 isn't available in
fc20 - Would still need to choose the right patch using version
in the spec file to support them both at the same time.

### CODE REVIEW

**Comment by marmarek** [comment]
This will most likely break fc20 build, so I'd prefer to not merge it into master yet. I see few options:
- leave it here and merge when Fedora 23 dom0 will be completed
- merge into some other branch, like `fedora-23`

Do you have any preference?

**Comment by jgriffiths** [comment]
@marmarek you can leave this here for now - I think I can update this to work for fc20 and 23 at the same time (when I get some time).

**Comment by jgriffiths** [comment]
It doesn't seem possible to provide both versions depending on DIST_DOM0 since its never passed down to the rpmbuild command. So there is no way to dynamically choose which version to use without changing the fedora builder.

So we'll probably have to leave this until the rest of fc23 dom0 is done.

**Comment by marmarek** [comment]
It has been cherry-picked.

**Pull request closed without merging**
